services:
  minio:
    container_name: minio
    image: minio/minio
    ports: 
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always
    
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  seq:
    image: datalust/seq:2021.4
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8001:80"
      
volumes:
  minio_data:
  mongo_data: